// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkdipbspSYrXea3iXHaCGj1MJHuTm2H_A',
    appId: '1:192256054977:web:737d870a8a091ccce52640',
    messagingSenderId: '192256054977',
    projectId: 'fir-memo-app-f9a73',
    authDomain: 'fir-memo-app-f9a73.firebaseapp.com',
    storageBucket: 'fir-memo-app-f9a73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj3vOUMRLMtD61OgSY9Yy9evv6rZCSQHs',
    appId: '1:192256054977:android:5e24e0fcd7cd283be52640',
    messagingSenderId: '192256054977',
    projectId: 'fir-memo-app-f9a73',
    storageBucket: 'fir-memo-app-f9a73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1j4FR_tr4U8-idy7ciqKOBCzfhMwCWYc',
    appId: '1:192256054977:ios:908144fc076f0cafe52640',
    messagingSenderId: '192256054977',
    projectId: 'fir-memo-app-f9a73',
    storageBucket: 'fir-memo-app-f9a73.appspot.com',
    iosBundleId: 'com.example.studyFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1j4FR_tr4U8-idy7ciqKOBCzfhMwCWYc',
    appId: '1:192256054977:ios:908144fc076f0cafe52640',
    messagingSenderId: '192256054977',
    projectId: 'fir-memo-app-f9a73',
    storageBucket: 'fir-memo-app-f9a73.appspot.com',
    iosBundleId: 'com.example.studyFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkdipbspSYrXea3iXHaCGj1MJHuTm2H_A',
    appId: '1:192256054977:web:e9b9d0d953749686e52640',
    messagingSenderId: '192256054977',
    projectId: 'fir-memo-app-f9a73',
    authDomain: 'fir-memo-app-f9a73.firebaseapp.com',
    storageBucket: 'fir-memo-app-f9a73.appspot.com',
  );
}
